name: MySQL To REST
description: |
  为您的MySQL数据库自动生成RESTful API
version: v0.1
category: Connector
maintainer: CloudMario <smcz@qq.com>
license: Apache License Version 2.0
projectURL: https://github.com/CloudSide
