runtime:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.network: true
  image: 192.168.0.86:5000/richarvey/nginx-php-fpm:php5
  environment:
    GIT_REPO: ${git_repo}
    GIT_BRANCH: ${git_branch}
    GIT_EMAIL: ${git_email}
    GIT_NAME: ${git_name}
    SSH_KEY: ${ssh_key}
    GIT_PERSONAL_TOKEN: ${git_personal_token}
    GIT_USERNAME: ${git_username}
    WEBROOT: ${webroot}
    ERRORS: ${errors}
    HIDE_NGINX_HEADERS: ${hide_nginx_headers}
    PHP_MEM_LIMIT: ${php_mem_limit}
    PHP_POST_MAX_SIZE: ${php_post_max_size}
    PHP_UPLOAD_MAX_FILESIZE: ${php_upload_max_filesize}
    RUN_SCRIPTS: ${run_scripts}
  volumes:
    - ${webroot_volume_name}:${webroot}
  cpuset: '1'
  cpu_shares: 512
  mem_limit: 268435456
  volume_driver: convoy-nfs
